import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StyledJsxRegistry from "./registry";
import Loader from "./Components/loader/page";
import Navbar from "./Components/navbar/page";
import HeaderSection from "./Components/headerSection/page";
import FooterPage from "./Components/footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rohit Kumar, Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Loader/>
      <StyledJsxRegistry>
        <Navbar/>
        <HeaderSection/>
        {children}
        <FooterPage/>
      </StyledJsxRegistry>
      </body>
    </html>
  );
}
